# CMT309/CMT314 - F2F Session 5
### 16/11/2021 - Tuesday

#### This example is constructed to work on descriptive statistics aby using `pandas` and `numpy` modules. 

#### You are given `csv` file which consists of 2020-2021 US National Basketball League NBA Play-off Series player statistics. For each player belongs to NBA teams taken part in Play-offs previous year, there are several important statistics, such as minutes per game, 3 points percentages, etc. (For details of each column please check the text files "columns_explained.txt") 

#### You are given a code block below, which imports important modules and downloads the data automatically. Please run it before starting the exercise.

In [1]:
import pandas as pd
import numpy as np
from urllib import request
module_url = f"https://drive.google.com/uc?export=view&id=1YBgN-LsQX82sjqulxUjcpyfuSu8aUqKG"
module_name = '20-21 NBA Player Stats.csv'
print(f'Fetching {module_url}')
with request.urlopen(module_url) as f, open(module_name,'w') as outf:
  a = f.read()
  outf.write(a.decode('utf-8'))
module_url2 = f"https://drive.google.com/uc?export=view&id=1uRr766AFbqJYhOng_wktr31laqWOZETz"
module_name2 = 'columns_explained.txt'
print(f'Fetching {module_url2}')
with request.urlopen(module_url2) as f, open(module_name2,'w') as outf:
  a = f.read()
  outf.write(a.decode('utf-8'))
df = pd.read_csv('20-21 NBA Player Stats.csv')
df.replace('', 0, inplace=True)
df = df.fillna(0.0)
df.head(5)

Fetching https://drive.google.com/uc?export=view&id=1YBgN-LsQX82sjqulxUjcpyfuSu8aUqKG
Fetching https://drive.google.com/uc?export=view&id=1uRr766AFbqJYhOng_wktr31laqWOZETz

,FULL NAME,TEAM,POS,AGE,GP,MPG,MIN%,USG%,TO%,FTA,...,RPG,TRB%,APG,AST%,SPG,BPG,TOPG,VI,ORTG,DRTG
0,Pat Connaughton,Mil,G,28.54,23,23.7,49.4,10.7,8.8,13,...,4.4,9.9,0.9,4.8,0.43,0.26,0.52,5.1,129.0,107.6
1,Bryn Forbes,Mil,G,28.00,20,13.7,28.5,19.2,5.7,8,...,1.4,5.3,0.3,3.1,0.10,0.10,0.35,4.1,110.1,110.5
2,Jrue Holiday,Mil,G,31.11,23,39.6,82.6,22.1,11.9,56,...,5.7,7.8,8.7,31.4,1.65,0.43,2.43,9.6,108.9,108.4
3,Brook Lopez,Mil,C,33.30,23,29.0,60.4,16.8,9.6,43,...,5.9,10.9,0.3,1.3,0.74,1.48,1.09,3.9,122.1,106.8
4,Khris Middleton,Mil,F,29.94,23,40.1,83.5,26.4,13.0,97,...,7.6,10.1,5.1,19.6,1.52,0.17,3.22,9.7,107.8,106.3

## Exercise

### Answer the questions below by using `pandas` and `numpy`.

**Example: Find and `print` the player who played more than 10 games and has the highest points per game value.**
```python
df_new = df[df.GP > 10]
print('The player with highest PPG rate is {} with a PPG of {:.2f} in {} games.'.
      format(' & '.join(df_new[df_new.PPG == np.max(df_new.PPG)]['FULL NAME']),
             np.max(df_new.PPG),
             int(df_new[df_new.PPG == np.max(df_new.PPG)]['GP'].values)))
```
```
The player with highest PPG rate is Kevin Durant with a PPG of 34.30 in 12 games.
```

**Now your turn 😏**

1. Create and `print` a new `pandas` dataframe `dsdf` which includes the information below:
```
          Mean       Std. Deviation    Variance
AGE    27.361144        4.304653    18.530036
GP      7.618644        5.514879    30.413890
MPG    18.059322       12.748208   162.516820
...
```



2. Calculate and `print` average AGE of the players (who played at least 10 minutes per game, e.g. MPG > 10) with youngest and oldest players. An example output is
```
Average age of the players who played at least 10 MPG is 28.35 with youngest Talen Horton-Tucker (20.65) and oldest Andre Iguodala (37.48).
```

3. Calculate and `print` average points per game (PPG) $\pm$ standard deviation with the maximum. An example output is
```
Average points per game (PPG) is 8.11 +/- 8.17 with maximum 35.70 (Luka Doncic).
```

4. Calculate and `print` total average successful 3 points attemps with the maximum and percentage rate. An example output is
```
Total Average successful 3 points attemps is 8.88 with maximum 60.00 (Khris Middleton) with 34.3% rate.
```

5. Calculate and `print` the team with the highest and lowest variance RPG values (hint: `.groupby()`). An example output is
```
Team with highest variance of Rebounds per game is Nyk with 11.64, and lowest variance of RPG is Bos with 6.33.
```

In [ ]:
# Some Stats for 2020-2021 NBA Playoff Series
# 1. Creating dsdf

# 2. Average Age of Players

# 3. Average Points Per Game

# 4. Total Average successful 3 points attemps (This is not a column in df! df has 3PA, 3P% and PG variables to calculate this.)

# 5. The team with Highest and Lowest variance of RPG (hint: .groupby)

In [4]:
def mean(data):
  n = len(data)
  mean = sum(data) / n
  return mean

def variance(data):
   
  n = len(data)
   
  mean = sum(data) / n
   
  deviations = [(x - mean) ** 2 for x in data]
    
  variance = sum(deviations) / n
  return variance

def stdev(data):
  import math
  var = variance(data)
  std_dev = math.sqrt(var)
  return std_dev

In [5]:
data = {'Mean': [mean(df.AGE),mean(df.GP), mean(df.MPG)], 'Std. Deviation': [stdev(df.AGE), mean(df.GP), mean(df.MPG)], 'Variance': [variance(df.AGE), variance(df.GP), variance(df.MPG)]}

In [15]:
dfds = pd.DataFrame(data,index=['AGE', 'GP', 'MPG'])

In [16]:
dfds.head(5)

          Mean  Std. Deviation    Variance
AGE  27.384435        4.285233   18.363224
GP    7.799163        7.799163   32.620752
MPG  18.154812       18.154812  162.621807